wcst_color_list = ['red', 'green', 'blue', 'yellow']
wcst_shape_list = ['circle', 'triangle', 'crosses', 'star']
wcst_count_list = [1, 2, 3, 4]
default_criteria_card_list=[{'color': 'red', 'shape': 'circle', 'count': 1},
                                {'color': 'green', 'shape': 'triangle', 'count': 2},
                                {'color': 'blue', 'shape': 'crosses', 'count': 3},
                                {'color': 'yellow', 'shape': 'star', 'count': 4}]

wcst_card_list1 = [{'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'}]
wcst_card_list2 = [{'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[0]'},
                   {'color': 'wcst_color_list[1]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[0]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[2]', 'count': 'wcst_count_list[2]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[1]', 'count': 'wcst_count_list[1]'},
                   {'color': 'wcst_color_list[2]', 'shape': 'wcst_shape_list[3]', 'count': 'wcst_count_list[3]'},
                   {'color': 'wcst_color_list[3]', 'shape': 'wcst_shape_list[0]', 'count': 'wcst_count_list[0]'}]

wcst_card_list1 = [{
    'color': eval(card['color']),
    'shape': eval(card['shape']),
    'count': eval(card['count'])
} for card in wcst_card_list1]

wcst_card_list2 = [{
    'color': eval(card['color']),
    'shape': eval(card['shape']),
    'count': eval(card['count'])
} for card in wcst_card_list2]

grid_positions = {
    1: [4],
    2: [1, 7],
    3: [1, 6, 8],
    4: [0, 2, 6, 8],
}

